"""
pipeline/state.py
─────────────────
Shared TypedDict that defines the LangGraph agent state.
"""

from typing import TypedDict, List, NotRequired


class AgentState(TypedDict):
    idea: str
    user_name: str
    ideal_customer: str
    problem_solved: str
    search_results: str
    analysis: str
    is_new_chat: bool
    conversation_id: str
    messages: List[str]
    conversation_history: List[dict]
    optimized_query: str          # legacy single-query (kept for DB persistence)
    optimized_queries: List[str]  # multiple targeted queries generated by LLM
    current_message: str
    input_valid: NotRequired[bool]
    validation_message: NotRequired[str]
    # ── LLM Vagueness Gate ───────────────────────────────────────────────────
    is_vague: NotRequired[bool]          # True if idea is too vague to analyse
    vague_message: NotRequired[str]      # User-facing message when idea is vague
    # ── QA flow fields (optional) ────────────────────────────────────────────
    question: NotRequired[str]
    qa_retrieval_query: NotRequired[str]
    rag_context: NotRequired[str]
    top_chunks: NotRequired[List[dict]]
    qa_answer: NotRequired[str]
    trace: NotRequired[List[dict]]
    # ── QA Memory (sliding window + LLM summary) ─────────────────────────────
    qa_history: NotRequired[List[dict]]   # full list of {"q": ..., "a": ...} turns
    qa_summary: NotRequired[str]          # LLM-compressed summary of older turns
