"""
pipeline/state.py
─────────────────
Shared TypedDict that defines the LangGraph agent state.
"""

from typing import TypedDict, List, NotRequired, Any


class AgentState(TypedDict):
    idea: str
    user_name: str
    ideal_customer: str
    problem_solved: str
    search_results: str
    analysis: str
    is_new_chat: bool
    conversation_id: str
    messages: List[str]
    conversation_history: List[dict]
    optimized_query: str          # legacy single-query (kept for DB persistence)
    optimized_queries: List[str]  # multiple targeted queries generated by LLM
    current_message: str
    engagement_question: NotRequired[str]
    input_valid: NotRequired[bool]
    validation_message: NotRequired[str]
    # ── LLM Vagueness Gate ───────────────────────────────────────────────────
    is_vague: NotRequired[bool]          # True if idea is too vague to analyse
    vague_message: NotRequired[str]      # User-facing message when idea is vague
    # ── QA flow fields (optional) ────────────────────────────────────────────
    question: NotRequired[str]
    qa_retrieval_query: NotRequired[str]
    rag_context: NotRequired[str]
    top_chunks: NotRequired[List[dict]]
    qa_answer: NotRequired[str]
    trace: NotRequired[List[dict]]
    # ── QA Memory (sliding window + LLM summary) ─────────────────────────────
    qa_history: NotRequired[List[dict]]   # full list of {"q": ..., "a": ...} turns
    qa_summary: NotRequired[str]          # LLM-compressed summary of older turns
    on_log: NotRequired[Any]              # Optional callback for real-time logging
    on_scrape_event: NotRequired[Any]     # Optional callback for structured URL scrape events
    should_refine: NotRequired[bool]      # True if the report needs to be updated based on Q&A
    refinement_reason: NotRequired[str]   # Explanation for why refinement was triggered/skipped
    # ── Idea refinement flow fields (optional) ───────────────────────────────
    refinement_text: NotRequired[str]
    refinement_query: NotRequired[str]
    is_valid_refinement: NotRequired[bool]
    refined_idea: NotRequired[str]
    refined_problem_solved: NotRequired[str]
    refined_ideal_customer: NotRequired[str]
    refinement_score_before: NotRequired[str]
    refinement_score_after: NotRequired[str]
    refinement_score_delta: NotRequired[int]
    refinement_summary: NotRequired[str]
    refinement_version: NotRequired[int]
