"""sync remaining schema

Revision ID: 843ff5581461
Revises: 20260505_01
Create Date: 2026-05-05 13:33:55.138796
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '843ff5581461'
down_revision = '20260505_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_mentor_requested')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_mentor_requested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
